name: "@bitx-sh/config"
version: 0.0.1
module: index.ts
type: module
private: true
repository:
  type: git
  url: git+https://github.com/bitx-sh/bitx-config.git
workspaces:
  - packages/*
scripts:
  build: bun run --cwd packages/core build
  dev: bun run --cwd packages/core dev
  test: bun test
  lint: biome check .
  format: biome format . --write
  clean: rm -rf **/dist **/node_modules
  prepare: simple-git-hooks
devDependencies:
  "@biomejs/biome": 1.9.4
  "@types/bun": latest
  "@types/node": latest
  changelogen: latest
  knip: latest
  lint-staged: latest
  publint: latest
peerDependencies:
  typescript: ^5.7.2
dependencies:
  c12: latest
  citty: latest
  consola: latest
  knitwork: latest
  mlly: latest
  pathe: latest
  pkg-types: latest
  quicktype: latest
  renovate: ^39.82.9
  scule: latest
  simple-git-hooks: latest
  std-env: latest
  unbuild: latest
  unconfig: latest
  unimport: latest
  zod: latest
author:
  name: Daniel Bodnar
  url: https://github.com/danielbodnar
engines:
  bun: ^1.1.40
cli:
  commands:
    - name: init
      description: Initialize a new configuration file
      subcommands:
        - name: project
          description: Set up project-specific configuration
        - name: user
          description: Set up user-specific configuration
    - name: get
      description: Retrieve a configuration value
    - name: set
      description: Set a configuration value
    - name: list
      description: List all configuration values
    - name: import
      description: Import configuration from a file
    - name: export
      description: Export configuration to a file
